using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Text;

namespace ProRepCongressLookup
{
    public enum Chamber
    {
        [Description("house")]
        House,
        [Description("senate")]
        Senate
    }

    public enum State
    {
        [Description("AL")]
        Alabama,
        [Description("AK")]
        Alaska,
        [Description("AZ")]
        Arizona,
        [Description("AR")]
        Arkansas,
        [Description("CA")]
        California,
        [Description("CO")]
        Colorado,
        [Description("CT")]
        Connecticut,
        [Description("DE")]
        Delaware,
        [Description("FL")]
        Florida,
        [Description("GA")]
        Georgia,
        [Description("HI")]
        Hawaii,
        [Description("ID")]
        Idaho,
        [Description("IL")]
        Illinois,
        [Description("IN")]
        Indiana,
        [Description("IA")]
        Iowa,
        [Description("KS")]
        Kansas,
        [Description("KY")]
        Kentucky,
        [Description("LA")]
        Louisiana,
        [Description("ME")]
        Maine,
        [Description("MD")]
        Maryland,
        [Description("MA")]
        Massachusetts,
        [Description("MI")]
        Michigan,
        [Description("MN")]
        Minnesota,
        [Description("MS")]
        Mississippi,
        [Description("MO")]
        Missouri,
        [Description("MT")]
        Montana,
        [Description("NE")]
        Nebraska,
        [Description("NV")]
        Nevada,
        [Description("NH")]
        NewHampshire,
        [Description("NJ")]
        NewJersey,
        [Description("NM")]
        NewMexico,
        [Description("NY")]
        NewYork,
        [Description("NC")]
        NorthCarolina,
        [Description("ND")]
        NorthDakota,
        [Description("OH")]
        Ohio,
        [Description("OK")]
        Oklahoma,
        [Description("OR")]
        Oregon,
        [Description("PA")]
        Pennsylvania,
        [Description("RI")]
        RhodeIsland,
        [Description("SC")]
        SouthCarolina,
        [Description("SD")]
        SouthDakota,
        [Description("TN")]
        Tennessee,
        [Description("TX")]
        Texas,
        [Description("UT")]
        Utah,
        [Description("VT")]
        Vermont,
        [Description("VA")]
        Virginia,
        [Description("WA")]
        Washington,
        [Description("WV")]
        WestVirginia,
        [Description("WI")]
        Wisconsin,
        [Description("WY")]
        Wyoming
    }

    public enum ExpenseCategory
    {
        [Description("travel")]
        Travel,
        [Description("personnel")]
        Personnel,
        [Description("rent-utilities")]
        RentUtilities,
        [Description("other-services")]
        OtherServices,
        [Description("supplies")]
        Supplies,
        [Description("franked-mail")]
        FrankedMail,
        [Description("printing")]
        printing,
        [Description("equipment")]
        Equipment,
        [Description("total")]
        Total
    }

    public enum BillType
    {
        [Description("introduced")]
        Introduced,
        [Description("updated")]
        Updated,
        [Description("active")]
        Active,
        [Description("passed")]
        Passed,
        [Description("enacted")]
        Enacted,
        [Description("vetoed")]
        Vetoed
    }

    public enum APIModelKeyWords
    {
        [Description("member_id")]
        MemberID,
        [Description("members")]
        Members,
        [Description("roles")] 
        Roles,
        [Description("committees")]
        Committees,
        [Description("subcommittees")]
        SubCommittees,
    }
}
